### ISSUE TITLE
Browser URL: undefined in Safari on 1.6

### ISSUE THREAD

**Issue by imathis** [mockko/livereload#69]
I've updated to 1.6 and when I initiate livereload in Safari, my console says "Browser URL: undefined" and it fails to initiate reloads of the browser on changes. I've updated Chrome to 1.6 and it works fine there. It seems that something has gone wrong with getting the url for Safari. Anything I can try or change? My extension settings are the defaults.

**Comment by NV** [comment]
Fix &quot;Browser URL: undefined&quot; in Safari.
Closed by 42e78ba3b9baa7df257ce6bc6ad3443ddcf96012.

**Comment by NV** [comment]
@imathis, does LiveReload Safari extension 1.6.1 work for you? 1.6 had a bug (fixed in 696edf842e3583f8d4d1a8446dbfcb218ee7a9fa).

"Browser URL: undefined" is a different issue I just fixed.

**Comment by trekdemo** [comment]
it's not working for me either
here's the log: https://gist.github.com/896154

update: i've just found that i was using gem with version 1.5. So i updated it, but the bug still exists.

**Comment by NV** [comment]
Why do you have debug mode turned on in em-websocket gem? Tell me the output of `gem list --local em-websocket`

**Comment by trekdemo** [comment]
I've turned on debug mode to get a verbose log:

```
$ gem list --local em-websocket

*** LOCAL GEMS ***

em-websocket (0.1.3)
```

**Comment by NV** [comment]
Try to use latest version (0.2.1).

```
gem install em-websocket
```
