### ISSUE TITLE
Problem with Firefox 6

### ISSUE THREAD

**Issue by lmartins** [mockko/livereload#87]
I've installed the new beta for Firefox 6 and im not getting the following error:

LiveReload failed to establish connection: WebSocket is not a constructor

Is this recoverable or should i wait for the final Firefox 6 release?

**Comment by andreyvit** [comment]
Firefox 6 has changed the web sockets protocol (AGAIN!!!111). Anyone wants to contribute a fix? :)

**Comment by knocte** [comment]
andreyvit, do you have any URL on the breaking changes that Firefox 6 introduced?

**Comment by NV** [comment]
Fixed by 503cf7cced619fb646cf176df64db675bb0267ca

**Comment by lmartins** [comment]
Still getting the error bellow in Firefox 6 final release:

LiveReload failed to establish connection: WebSocket is disabled.
To turn it on, open about:config and set network.websocket.override-security-block to true.

I have the config property configured as described. Any further suggestion?

**Comment by NV** [comment]
Do you have [LR version 0.6.3](https://addons.mozilla.org/en-US/firefox/addon/livereload/versions/#version-0.6.3) installed? It hasn't been reviewed yet, so https://addons.mozilla.org/en-US/firefox/addon/livereload/ shows the broken version.

**Comment by lmartins** [comment]
Thanks, i was using the previous version. I've now installed the latest one, had to push the LR button to the toolbar but nothing happens when i push it. Before it would turn green and the LR logo on the menubar would go darker. 

Im also using the latest version of LR itself.

Am I'm missing something?

**Comment by NV** [comment]
I assume you're using Livereload.app. Which version?

**Comment by lmartins** [comment]
Yes, I'm using the Livereload.app in version 2.0 alpha5
Thanks.

**Comment by NV** [comment]
Hm, same version works fine for me.

**Comment by lmartins** [comment]
I does now for me too. I have no idea why i didn't before, at the time i had restarted both apps.
Thanks! :-)

**Comment by jrefano** [comment]
I've got Firefox 6.0.1, Livereload extension 0.6.3 (linked above), and am getting 

Cannot connect to LiveReload server:
ws://localhost:35729/websocket

Any ideas?

**Comment by NV** [comment]
Seems like livereload server is shut down. Have you tried Chrome or Safari extension? Did it work?

**Comment by clonn** [comment]
I have the same problem, but my situation is a little bit different. My firefox can connect to ws:// protocol, but after a while (maybe 20 seconds) console is displayed error message, then it is fail to connect to server.
So far I have no idea about it.
